### ISSUE TITLE
Cadê o README.MD?

### ISSUE THREAD

**Issue by fabiosantosrj** [MigPlayer6032/horadecodar_bot#1]
Olá,

Eu gostaria de saber o que esse código faz. Mas, não tem um descritivo com o README.md.

**Comment by migtibincoski** [comment]
Olá, @fabiosantosrj, tudo bem?

Fico feliz que você teve interesse no meu repositório. Obrigado!
Já criei o arquivo `README.md` na raiz do projeto. [Clique aqui](../) para ver.

Qualquer coisa, você pode criar uma nova issue, pois vou fechar essa. Valeu!

Atenciosamente,
MIguel Tibincoski
